### ISSUE TITLE
Bug report for trillium-http/cookie: Panic on non ascii cookie

### ISSUE THREAD

**Issue by markusgod** [trillium-rs/trillium#88]
**Describe the bug**
There are situations where client can send a non ascii cookie, currently trillium panics when countering one, That can be a potential DOS attack.

**To Reproduce**
1. Set cookie value to non-ascii symbol in browser.
2. Send any request.

**Expected behavior**
At least not panic. May be skip this header and log error would be better.

Looks like this is beacuse of this unwrap.
```rust
pub fn insert(
        &mut self,
        name: impl Into<HeaderName>,
        values: impl ToHeaderValues,
    ) -> Option<HeaderValues> {
        let name = name.into();
        let values: HeaderValues = values.to_header_values().unwrap().collect();
        self.headers.insert(name, values)
    }
```

**Log**
```
TRACE trillium_http::conn: in head, finished headers:
 GET / HTTP/1.1
Host: localhost:8080
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
DNT: 1
Connection: keep-alive
Cookie: {78b7507b-cd4e-484e-a1f0-090e7cabdc22}=фыв
Upgrade-Insecure-Requests: 1
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: none
Sec-Fetch-User: ?1
Sec-GPC: 1
Cache-Control: max-age=0    
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: String slice should be valid ASCII', /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/trillium-http-types-0.0.3/src/headers/headers.rs:54:62
stack backtrace:
   0: rust_begin_unwind
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/result.rs:1355:5
   3: core::result::Result<T,E>::unwrap
             at /home/mark/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:1037:23
   4: trillium_http_types::headers::headers::Headers::insert
             at /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/trillium-http-types-0.0.3/src/headers/headers.rs:54:36
   5: trillium_http::conn::Conn<Transport>::new::{{closure}}
             at /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/trillium-http-0.1.7/src/conn.rs:498:13
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/mark/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
   7: trillium_http::conn::Conn<Transport>::next::{{closure}}
             at /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/trillium-http-0.1.7/src/conn.rs:686:9
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/mark/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
   9: trillium_http::conn::Conn<Transport>::finish::{{closure}}
             at /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/trillium-http-0.1.7/src/conn.rs:721:19
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/mark/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  11: trillium_http::conn::Conn<Transport>::send::{{closure}}
             at /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/trillium-http-0.1.7/src/conn.rs:174:22
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/mark/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  13: trillium_http::conn::Conn<Transport>::map::{{closure}}
             at /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/trillium-http-0.1.7/src/conn.rs:148:26
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/mark/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  15: <trillium_server_common::config::Config<ServerType,AcceptorType> as trillium_server_common::config_ext::ConfigExt<ServerType,AcceptorType>>::handle_stream::{{closure}}
             at /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/trillium-server-common-0.1.2/src/config_ext.rs:154:22
  16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/mark/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  17: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /home/mark/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs:120:9
  18: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/task/core.rs:243:17
  19: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/loom/std/unsafe_cell.rs:14:9
  20: tokio::runtime::task::core::CoreStage<T>::poll
             at /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/task/core.rs:233:13
  21: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/task/harness.rs:438:23
  22: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /home/mark/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:344:9
  23: std::panicking::try::do_call
             at /home/mark/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:379:40
  24: __rust_try
  25: std::panicking::try
             at /home/mark/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:343:19
  26: std::panic::catch_unwind
             at /home/mark/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:431:14
  27: tokio::runtime::task::harness::poll_future
             at /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/task/harness.rs:425:19
  28: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/task/harness.rs:89:9
  29: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/task/harness.rs:59:15
  30: tokio::runtime::task::raw::poll
             at /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/task/raw.rs:113:5
  31: tokio::runtime::task::raw::RawTask::poll
             at /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/task/raw.rs:70:18
  32: tokio::runtime::task::Notified<S>::run
             at /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/task/mod.rs:171:9
  33: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
             at /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/thread_pool/worker.rs:349:13
  34: tokio::coop::with_budget::{{closure}}
             at /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/coop.rs:106:9
  35: std::thread::local::LocalKey<T>::try_with
             at /home/mark/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:376:16
  36: std::thread::local::LocalKey<T>::with
             at /home/mark/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:352:9
  37: tokio::coop::with_budget
             at /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/coop.rs:99:5
  38: tokio::coop::budget
             at /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/coop.rs:76:5
  39: tokio::runtime::thread_pool::worker::Context::run_task
             at /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/thread_pool/worker.rs:348:9
  40: tokio::runtime::thread_pool::worker::Context::run
             at /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/thread_pool/worker.rs:318:24
  41: tokio::runtime::thread_pool::worker::run::{{closure}}
             at /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/thread_pool/worker.rs:303:17
  42: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/macros/scoped_tls.rs:61:9
  43: tokio::runtime::thread_pool::worker::run
             at /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/thread_pool/worker.rs:300:5
  44: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
             at /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/thread_pool/worker.rs:279:45
  45: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/blocking/task.rs:42:21
  46: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/task/core.rs:243:17
  47: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/loom/std/unsafe_cell.rs:14:9
  48: tokio::runtime::task::core::CoreStage<T>::poll
             at /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/task/core.rs:233:13
  49: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/task/harness.rs:438:23
  50: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /home/mark/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:344:9
  51: std::panicking::try::do_call
             at /home/mark/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:379:40
  52: __rust_try
  53: std::panicking::try
             at /home/mark/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:343:19
  54: std::panic::catch_unwind
             at /home/mark/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:431:14
  55: tokio::runtime::task::harness::poll_future
             at /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/task/harness.rs:425:19
  56: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/task/harness.rs:89:9
  57: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/task/harness.rs:59:15
  58: tokio::runtime::task::raw::poll
             at /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/task/raw.rs:113:5
  59: tokio::runtime::task::raw::RawTask::poll
             at /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/task/raw.rs:70:18
  60: tokio::runtime::task::Notified<S>::run
             at /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/task/mod.rs:171:9
  61: tokio::runtime::blocking::pool::Inner::run
             at /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/blocking/pool.rs:265:17
  62: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/blocking/pool.rs:245:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by jbr** [comment]
I think there might be a few issues here, in priority order
* The tokio runtime adapter should have better panic recovery handling.  For comparison, the smol runtime continues to accept requests after panic. I believe it should be possible to add similar somewhat-graceful panic unwinding to tokio as well
* Cookie headers should be percent encoded
* Headers that cannot be converted to ascii should be handled more gracefully
